server:
  #address: 0.0.0.0
  #port config, Hugging Face Spaces require port 7860
  port: 7860

  tomcat:
    accesslog:
      enabled: true
      pattern: "%h %l %u %t \"%r\" %s %b"
      
management:
  endpoints:
    web:
      exposure:
        include: health,info     
